export const ProductService = {
  getProductsData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Panda Motors',
        description: 'High-quality motor oil for your vehicle.',
        image: 'https://www.cna.com.tn/files/palma-0.jpg',
        price: 65,
        category: 'Accessories',
        quantity: 24,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1001',
        code: 'nvklal433',
        name: 'Panda Motors',
        description: 'Reliable motor battery.',
        image: 'https://www.cna.com.tn/files/slide03.png',
        price: 72,
        category: 'Accessories',
        quantity: 61,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1003',
        code: '244wgerg2',
        name: 'Panda Motors',
        description: 'Quality engine parts and accessories.',
        image: 'https://www.cna.com.tn/files/panda_motors.png',
        price: 29,
        category: 'Clothing',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'Car Air Freshener',
        description: 'Keeps your car smelling fresh.',
        image: 'https://www.cna.com.tn/files/slide01.png',
        price: 10,
        category: 'Accessories',
        quantity: 100,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1005',
        code: 'we45t6yu7',
        name: 'Tire Inflator',
        description: 'Portable tire inflator for emergencies.',
        image: 'https://www.cna.com.tn/files/palma-3.jpg',
        price: 45,
        category: 'Tools',
        quantity: 15,
        inventoryStatus: 'LOWSTOCK',
        rating: 5,
      },
      {
        id: '1006',
        code: 'zsdf2345',
        name: 'Car Cover',
        description: 'Protect your car from the elements.',
        image: 'https://www.cna.com.tn/files/palma-4.jpg',
        price: 55,
        category: 'Accessories',
        quantity: 30,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1007',
        code: 'xcv5678',
        name: 'Brake Pads',
        description: 'Durable and high-quality brake pads for safety.',
        image: 'https://www.cna.com.tn/files/slide04.png',
        price: 80,
        category: 'Automotive',
        quantity: 40,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1008',
        code: 'bnm2345',
        name: 'Car Vacuum Cleaner',
        description: 'Compact car vacuum cleaner for easy cleaning.',
        image: 'https://www.cna.com.tn/files/palma-2.jpg',
        price: 35,
        category: 'Tools',
        quantity: 20,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1009',
        code: 'jkl7890',
        name: 'Windshield Wiper',
        description: 'High-performance windshield wipers.',
        image: 'https://www.cna.com.tn/files/palma-1.jpg',
        price: 25,
        category: 'Automotive',
        quantity: 50,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
    ]
  },

  getProducts() {
    return Promise.resolve(this.getProductsData())
  },
}
